// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teletrome.API.Data;

#nullable disable

namespace Teletrome.API.Data.Migrations
{
    [DbContext(typeof(TeletromeDbContext))]
    partial class TeletromeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Teletrome.API.Entities.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_builds_project_id");

                    b.HasIndex("ProjectId", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_build");

                    b.ToTable("builds", (string)null);
                });

            modelBuilder.Entity("Teletrome.API.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("FunctionRegistryId")
                        .HasColumnType("int")
                        .HasColumnName("function_registry_id");

                    b.Property<int>("InstallId")
                        .HasColumnType("int")
                        .HasColumnName("install_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.HasIndex("FunctionRegistryId")
                        .HasDatabaseName("ix_events_function_registry_id");

                    b.HasIndex("InstallId")
                        .HasDatabaseName("ix_events_install_id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Teletrome.API.Entities.FunctionRegistryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildId")
                        .HasColumnType("int")
                        .HasColumnName("build_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("file_name");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("function_name");

                    b.HasKey("Id");

                    b.HasIndex("BuildId")
                        .HasDatabaseName("ix_function_registry_build_id");

                    b.HasIndex("BuildId", "FunctionName", "FileName")
                        .IsUnique()
                        .HasDatabaseName("uq_function");

                    b.ToTable("function_registry", (string)null);
                });

            modelBuilder.Entity("Teletrome.API.Entities.Install", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("InstallId")
                        .IsRequired()
                        .HasColumnType("char(36)")
                        .HasColumnName("install_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_installs_project_id");

                    b.HasIndex("ProjectId", "InstallId")
                        .IsUnique()
                        .HasDatabaseName("uq_install");

                    b.ToTable("installs", (string)null);
                });

            modelBuilder.Entity("Teletrome.API.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("api_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Teletrome.API.Entities.Build", b =>
                {
                    b.HasOne("Teletrome.API.Entities.Project", "Project")
                        .WithMany("Builds")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Teletrome.API.Entities.Event", b =>
                {
                    b.HasOne("Teletrome.API.Entities.FunctionRegistryEntry", "FunctionRegistryEntry")
                        .WithMany("Events")
                        .HasForeignKey("FunctionRegistryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Teletrome.API.Entities.Install", "Install")
                        .WithMany("Events")
                        .HasForeignKey("InstallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FunctionRegistryEntry");

                    b.Navigation("Install");
                });

            modelBuilder.Entity("Teletrome.API.Entities.FunctionRegistryEntry", b =>
                {
                    b.HasOne("Teletrome.API.Entities.Build", "Build")
                        .WithMany("Functions")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Build");
                });

            modelBuilder.Entity("Teletrome.API.Entities.Install", b =>
                {
                    b.HasOne("Teletrome.API.Entities.Project", "Project")
                        .WithMany("Installs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Teletrome.API.Entities.Build", b =>
                {
                    b.Navigation("Functions");
                });

            modelBuilder.Entity("Teletrome.API.Entities.FunctionRegistryEntry", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Teletrome.API.Entities.Install", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Teletrome.API.Entities.Project", b =>
                {
                    b.Navigation("Builds");

                    b.Navigation("Installs");
                });
#pragma warning restore 612, 618
        }
    }
}
